PexesoWebApp/Controllers/PexesoController.cs
using System.ServiceModel;
using System.Web.Mvc;
using GameService.Library;
using GameService.Library.Models;

namespace PexesoWebApp.Controllers
{
    public class PexesoController : Controller
    {
        private InstanceContext Ctx => new InstanceContext(new PexesoEventHandler());

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Player player)
        {
            var channelFactory = new DuplexChannelFactory<IGameService>(Ctx, "GameServiceEndPoint");
            var service = channelFactory.CreateChannel();

            try
            {
                var registered = service.RegisterPlayer(player.Name, player.Password);
                if (registered != null)
                {
                    return View("RegistrationSuccess");
                }

                return View("RegistrationError");
            }
            catch
            {
                return View("ServiceNotAvailable");
            }
        }

        public ActionResult Statistics()
        {
            var channelFactory = new DuplexChannelFactory<IGameService>(Ctx, "GameServiceEndPoint");
            var service = channelFactory.CreateChannel();
            try
            {   
                return View(service.GetGamesStatistics());
            }
            catch
            {
                return View("ServiceNotAvailable");
            }
        }

        public ActionResult Players()
        {
            var channelFactory = new DuplexChannelFactory<IGameService>(Ctx, "GameServiceEndPoint");
            var service = channelFactory.CreateChannel();
            try
            {
                return View(service.GetRegisteredPlayers());
            }
            catch
            {
                return View("ServiceNotAvailable");
            }
        }
    }
}

PexesoWebApp/Views/Pexeso/Index.cshtml
@{
    ViewBag.Title = "Pexeso homepage";
}

<h2>@ViewBag.Title</h2>
<p>
    Pexeso je karetní hra pro nejméně dva hráče zaměřená na paměť a soustředění. Její původní název je Memory (anglicky Paměť).
    Název PEXESO je český akronym vzniklý ze sousloví PEKELNĚ SE SOUSTŘEĎ.
    Hraje se se speciální sadou karet. Balíček se skládá ze sudého počtu, nejčastěji 64 karet, které tvoří dvojice.
    Cílem hry je nalézt co nejvíce dvojic.
</p>

<button type="button" class="btn" onclick="location.href='@Url.Action("Register", "Pexeso")'" >Register new player</button>
<button type="button" class="btn" onclick="location.href='@Url.Action("Statistics", "Pexeso")'" >Game statistics</button>
<button type="button" class="btn" onclick="location.href='@Url.Action("Players", "Pexeso")'">Registered players</button>

PexesoWebApp/Views/Pexeso/Players.cshtml
@model List<GameService.Library.Models.Player>

@{
    ViewBag.Title = "Registered players";
}

<h2>Registered players</h2>

<table class="table">
    <thead>
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr scope="row">
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
        </tr>
    }
    </tbody>
</table>

PexesoWebApp/Views/Pexeso/Register.cshtml
@model GameService.Library.Models.Player

@{
    ViewBag.Title = "Register";
}

<h2>@ViewBag.Title.</h2>
<p>Name and password must be at least 5 characters long.</p>

@using (Html.BeginForm("Register", "Pexeso", FormMethod.Post))
{
    <table class="table">
        <tr>
            <th>Register new player</th>
        </tr>
        <tr>
            <td>Name:</td>
            <td>
                @Html.TextBoxFor(player => player.Name)
            </td>
        </tr>
        <tr>
            <td>Password: </td>
            <td>
                @Html.PasswordFor(player => player.Password)
            </td>
        </tr>     
        <tr>
            <td></td>
            <td><input type="submit" value="Submit"/></td>
        </tr>
    </table>
}

PexesoWebApp/Views/Pexeso/RegistrationError.cshtml
@{
    ViewBag.Title = "Registration error";
}

<h2>Error! This player couldn't be registered.</h2>

PexesoWebApp/Views/Pexeso/RegistrationSuccess.cshtml
@model GameService.Library.Models.Player

@{
    ViewBag.Title = "Registration Success";
}

<h2>Player @Html.DisplayFor((player => player.Name)) has been created.</h2>

PexesoWebApp/Views/Pexeso/ServiceNotAvailable.cshtml
@{
    ViewBag.Title = "ServiceNotAvailable";
}

<h2>Error! Service is not available</h2>

PexesoWebApp/Views/Pexeso/Statistics.cshtml
@model List<GameService.Library.Models.GameStatistic>

@{
    ViewBag.Title = "Game Statistics";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First player</th>
            <th scope="col">Second player</th>
            <th scope="col">First player score</th>
            <th scope="col">Second player score</th>
            <th scope="col">Game size</th>
            <th scope="col">Game duration</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr scope="row">
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstPlayer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SecondPlayer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstPlayerScore)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SecondPlayerScore)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GameSize)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GameDuration)
                </td>
            </tr>
        }
    </tbody>
</table>

PexesoWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pexeso</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pexeso", "Index", "Pexeso", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Register", "Register", "Pexeso")</li>
                    <li>@Html.ActionLink("Statistics", "Statistics", "Pexeso")</li>
                    <li>@Html.ActionLink("Registered players", "Players", "Pexeso")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>